version: "3.7"
services:
    workspace-api:
        build: .
        ports:
        - 5000:5000
        volumes:
        - .:/srv/service        
        env_file: test_environment.env
        command: uvicorn --reload --host=0.0.0.0 --port 5000 --log-level=info --reload workspace_api:app
