@baseUrl = http://localhost:5000
#@baseUrl = https://workspace-api.apx.develop.eoepca.org

### create Workspace

POST {{baseUrl}}/workspaces/
Content-Type: application/json

{
  "preferred_name": "joe2"
}

### get Workspace Alice

GET {{baseUrl}}/workspaces/ws-alice
Content-Type: application/json

### get Workspace Joe

GET {{baseUrl}}/workspaces/ws-joe
Content-Type: application/json
