name: main

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - id: meta
        shell: bash
        run: |
          OWNER='${{ github.repository_owner }}'
          REPO='${{ github.event.repository.name }}'
          IMAGE="ghcr.io/${OWNER}/${REPO}"
          RAW_TAG="${GITHUB_REF_NAME}"
          V_TAG="v${RAW_TAG#v}"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tag=${V_TAG}" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.meta.outputs.tag }}
