name: main

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+" # 1.2.3
      - "[0-9]+\\.[0-9]+\\.[0-9]+-alpha\\.[0-9]+" # 1.2.3-alpha.1
      - "[0-9]+\\.[0-9]+\\.[0-9]+-beta\\.[0-9]+" # 1.2.3-beta.1
      - "[0-9]+\\.[0-9]+\\.[0-9]+-rc\\.[0-9]+" # 1.2.3-rc.1

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - id: meta
        shell: bash
        run: |
          OWNER="$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          REPO="$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')"
          IMAGE="ghcr.io/${OWNER}/${REPO}"
          RAW_TAG="${GITHUB_REF_NAME}"
          V_TAG="v${RAW_TAG#v}"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tag=${V_TAG}" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.meta.outputs.tag }}
